### ISSUE TITLE
The -n flag isn't being observed

### ISSUE THREAD

**Issue by hikumealan** [codsen/codsen#12]
**Package's name**
json-sort-cli

**Describe the bug**
Running the `json-sort-cli` package without the `-n` flag modifies the `node_modules` folders as well as the `package-lock.json` file

**To Reproduce**

1. `npx json-sort-cli **/*.json -d`

For my project with `lodash` as the only dependency - this command results with:
```
> npx json-sort-cli **/*.json -d

npx: installed 217 in 9.257s
✨ json-sort-cli: We'd try to sort the following files:
.eslintrc.json
.prettierrc.json
package-lock.json
package.json
node_modules/lodash/package.json
```

**Expected behavior**
According to the documentation the `-n` flag should be the only way to enable the modification of these files. 
However, this is occurring even without passing that flag - I would expect the `node_modules` folders and the `package-lock.json` file would be ignored in this case.

**Screenshots**

**Additional context**

**Comment by revelt** [comment]
hi Bryan, sorry for delay, yes it's a bug, I can see the default being set to `true`, [it's this line](https://github.com/codsen/codsen/blob/559932644e7f4dbbf14780fb8caef5e7318c8ea8/packages/json-sort-cli/cli.js#L77). It must have slipped through during the latest `meow` api change, when the flags validation was introduced. Sorry about that. I'll fix and beef up the test suite.

**Comment by revelt** [comment]
I've just double-checked the situation; the bug has been solved long time ago. The `package.json` sorting is a feature, not a bug, we use [`sort-package-json`](https://www.npmjs.com/package/sort-package-json) for that, otherwise, the sorting is alphabetical. Some time ago, there was a bug with lockfiles, they slipped through but it has been fixed long time ago. I'll close now. Thank you for taking time to report the bug.
