### ISSUE TITLE
Keep href value in link

### ISSUE THREAD

**Issue by loretoparisi** [codsen/codsen#15]
Is it possibile  with the current api to keep both the content and the `href` value in the `<a>` tag?

Example:

```javascript
stripHtml(`<a href="https://twitter.com/loretparisi">twitter:loretparisi&nbsp;&oslash;</a>`).result
"https://twitter.com/loretparisi twitter:loretparisi ø"
```

**Comment by revelt** [comment]
hi! Which package is it for? I suspect `string-strip-html`?

**Comment by loretoparisi** [comment]
@revelt yes sorry:

```nodejs
var { stripHtml }  = require("string-strip-html")
stripHtml(`<a href="https://twitter.com/loretparisi">twitter:loretparisi&nbsp;&oslash;</a>`).result
```

**Comment by revelt** [comment]
seems doable, using `opts.cb`:

```js
// Retain href and link label

import { strict as assert } from "assert";
import { stripHtml } from "../dist/string-strip-html.esm.js";

const someHtml = `<a href="https://twitter.com/loretparisi">twitter:loretparisi&nbsp;&oslash;</a>`;

assert.equal(
  stripHtml(someHtml, {
    skipHtmlDecoding: true,
  }).result,
  `twitter:loretparisi&nbsp;&oslash;`
);

assert.equal(
  stripHtml(someHtml, {
    skipHtmlDecoding: true,
    cb: ({ tag, deleteFrom, deleteTo, insert, rangesArr, proposedReturn }) => {
      let temp;
      if (
        tag.name === "a" &&
        tag.attributes &&
        tag.attributes.some((attr) => {
          if (attr.name === "href") {
            temp = attr.value;
            return true;
          }
        })
      ) {
        rangesArr.push([deleteFrom, deleteTo, `${temp} ${insert}`]);
      } else {
        rangesArr.push(proposedReturn);
      }
    },
  }).result,
  `https://twitter.com/loretparisi twitter:loretparisi&nbsp;&oslash;`
);

```

**Comment by revelt** [comment]
if you're happy I'll close

**Comment by loretoparisi** [comment]
Wow! `opts.cb` is extremely powerful!  Thanks a lot 💯

**Comment by loretoparisi** [comment]
@revelt sorry quick question how access the value of the  `tag` object while parsing the html in the `cb` callback you showed to me? hence  the value `twitter:loretparisi&nbsp;&oslash;` in`<a href="https://twitter.com/loretparisi">twitter:loretparisi&nbsp;&oslash;</a>`

Thanks!

```javascript
cb: ({ tag, deleteFrom, deleteTo, insert, rangesArr, proposedReturn }) => {
      let temp;
      if (
        tag.name === "a" &&
        tag.attributes &&
        tag.attributes.some((attr) => {
          if (attr.name === "href") {
            temp = attr.value;
            return true;
          }
        })
      ) {
        rangesArr.push([deleteFrom, deleteTo, `${temp} ${insert}`]);
      } else {
        rangesArr.push(proposedReturn);
      }
    }
    ```

**Comment by revelt** [comment]
> how do you access the value of the tag object?

If I understood the question right, you want to first view and then later do something on the tag object.
I always `console.log` everything "for research purposes" first, I always check what are the values. `JSON.stringify` is great because it automatically nicely prints non-circular data structures (99% of usual code).

```js
cb: ({ tag, deleteFrom, deleteTo, insert, rangesArr, proposedReturn }) => {
    console.log(JSON.stringify(tag, null, 4));
    console.log(JSON.stringify(deleteFrom, null, 4));
    // ^^^ and so on, log them, see what's inside
    let temp;
    // ...
```

> I have also found out that it is possible the preserve the url doing so
Oh yes, the `opts.dumpLinkHrefsNearby` is an automated solution, try that. If you need extra customisation, you can always patch up using `opts.cb`...

**Comment by loretoparisi** [comment]
@revelt thanks a lot, digging into the `tag` object it seems that the data structure does not keep the value of the tag  ((i.e. `element.innerHTML` ), but strangely attributes and positions only:

```
"{\n    \"attributes\": [\n        {\n            \"nameSta…    \"name\": \"a\",\n    \"lastClosingBracketAt\": 41\n}"
```

If I find how, I will post here.

**Comment by revelt** [comment]
in theory, if you slice `<originalSourceString>.slice(deleteFrom, deleteTo + 1)`, you'd get bracket-to-bracket

**Comment by paulthemagno** [comment]
That's an interesting task.

@revelt starting with this string:
```
<a href="https://twitter.com/loretparisi">twitter:loretparisi&nbsp;&oslash;</a>
```

with `<originalSourceString>.slice(deleteFrom, deleteTo + 1)` you should get `<a href="https://twitter.com/loretparisi">` if I'm not wrong. How to get `twitter:loretparisi&nbsp;&oslash;` instead? 

I tried to print these values:`tag, deleteFrom, deleteTo, insert, rangesArr, proposedReturn` but none of them was `twitter:loretparisi&nbsp;&oslash;` (I thought it was the variable `insert` but it returned an empty string `""`.

**Comment by revelt** [comment]
@paulthemagno Let me explain. When we need to mark multiple amendments on string, we need a way to mark "delete from this index to this index", or "delete from this to this but also insert this". Solution — Ranges. It's just array of arrays: [[0, 1], [3,4, "add"]] — means delete from index 0 to index 1; then replace slice between index 3 and 4 with "add".

I suspect what is happening, since callback API is consistent, it had to serve something for "insert", so it gives you an empty string, meaning: replace `[deleteFrom, deleteTo]` with empty string. If third element in a range array is missing, `null` or an empty string, it's the same — deletion.

Conceptually, there's no way to get `twitter:loretparisi&nbsp;&oslash;` because program only processes the HTML tags, opening `<a>` separately from `</a>`...

In theory, one way to "get" `twitter:loretparisi&nbsp;&oslash;` tied to the tag pair would be to use a parser (like [this](https://www.npmjs.com/package/codsen-parser)), traverse (for example using [this](https://www.npmjs.com/package/ast-monkey)), push each tag location to let's say same Ranges (using [this](https://www.npmjs.com/package/ranges-push)), then apply them onto a string (using [this](https://www.npmjs.com/package/ranges-apply)). I'm doing exact same thing in `stristri`, https://www.npmjs.com/package/stristri — it's also an HTML stripping tool but based off a tokenizer — 164 lines of code.

But that above might be overkill, try the callback, replacing tag-by-tag.

It depends what you need to achieve, I can draw up more examples if it helps. Also, have a look at [existing examples](https://codsen.com/os/string-strip-html/examples/).

**Comment by paulthemagno** [comment]
thanks @revelt. Can you kindly tell me in what point of your code you extract the value between the 2 tags ? `<a href="URL">"VALUE"</a>`.

I've a similar issue of @loretoparisi: I have to keep both `URL` and `VALUE` in a common text with a custom logic.

**Comment by revelt** [comment]
> Can you kindly tell me in what point of your code you extract the value between the 2 tags ?

We don't extract it at all, we just strip each tag, opening and closing, separately! Of course, unless you set the tag pair to be stripped using `opts.stripTogetherWithTheirContents`, I never thought that deep, I guess in tag pair stripping scenarios it would help to have child node contents fed in the callback...

In that original example I posted above, the presence of `href` implies it's an opening tag, so closing tag just gets removed, no special "treatment" for it.
