### ISSUE TITLE
Performance issues with codsen-parser

### ISSUE THREAD

**Issue by avigoldman** [codsen/codsen#19]
**Package's name**
codsen-parser

**Describe the bug**
Performance issues with parsing larger blocks of HTML.

**To Reproduce**
I created a repo running benchmarks against cparser and cheerio. https://github.com/avigoldman/cparser-vs-cheerio/

**Expected behavior**
I expected cparser to perform close to cheerio for parsing large blocks of HTML. Here are the results I got:
```
cheerio x 159 ops/sec ±2.74% (75 runs sampled)
cparser x 2.20 ops/sec ±8.64% (10 runs sampled)
```
https://github.com/avigoldman/cparser-vs-cheerio/blob/main/results.txt

**Additional context**

I'm trying to see if moving from cheerio to cparser is feasible. Right now the performance is blocking me from making the jump.

**Comment by revelt** [comment]
hi Avi! `codsen-parser` is aimed at broken code, the universal-ish ESP template language support is only a by-product. It will always be slower than `cheerio`. But `cheerio` will never cope with things like absent brackets, mismatching quote pairs, missing quotes and so on. I understand the bigger picture, maybe we should change the architecture and rebase, so that we have one codebase, but ship two parsers: one with error-catching clauses but slower, another without but faster. And ESP support goodies would be shared. As it is currently, it's indeed slow. Alternatively, I could go WebAssembly route, rewrite in Go and achieve not 159ops/sec but by magnitude more... Speaking of which, @avigoldman, theoretically, would you be able consume WebAssembly dependencies?

**Comment by avigoldman** [comment]
I think that approach makes a lot of sense. That'll benefit the performance for htmlcrush and email-comb too, since they are both focused on processing, not linting.

With a little effort I think I can have WebAssembly both on the frontend (nextjs) and node backend working!
