### ISSUE TITLE
declare type Range throw error

### ISSUE THREAD

**Issue by icksky** [codsen/codsen#4]
**Package's name**
Which package from the monorepo is it for?
`ranges-push` / `string-strip-html`
**Describe the situation**
Description of what is happening.
typescript throw error ` Cannot find name 'from'.` / `Cannot find name 'to'.` / `Cannot find name 'whatToInsert'.` from `/string-strip-html/types/index.d.ts(3,23)` and `ranges-push/types/index.d.ts(1,78)`
it's because of the defined of `Range` as shown below:
`declare type Range = [from: number, to: number] | [from: number, to: number, whatToInsert: string | null | undefined];`

Which version of Typescript supports this grammar definition?

**Comment by revelt** [comment]
hi! Sorry about the issue. Types were generated by `"typescript": "^4.2.3"`. Which one are you using?

**Comment by icksky** [comment]
@revelt Thanks for your reply. The ts's version is '^3.9.5' in my project.

**Comment by revelt** [comment]
hi @icksky How is it going? Happy Friday!

Generally, [union types](https://exploringjs.com/tackling-ts/ch_typescript-essentials.html#union-types) is a standard thing, I suspect it's just the location which is complaining, the problem is `null` is being passed somewhere. Basically, definitions are complaining that not an array is being passed to `ranges-push`, `null` probably.

Now, if it's `string-strip-html` somehow passing `null` internally, as a _range_ into `ranges-push`, then that's a bug but I can't find it without some clue because codebase is huge.

If it's your code calling something a wrong way (like using callback or something), then may or may not a bug. But if it's happening to you it will happen to somebody else and it still concerns me and it should be addressed.

**Can you post some code?** If it's closed-source, just post the area which calls `string-strip-html`, only lines which concerns it, feel free to rename variables/functions. Maybe I can spot something... You can even email it to me...

Also, can you extract some **input strings** you're testing upon? That would be handy too, as I can try sticking them into unit tests.

Sorry for the nuisance and thank you for considering `string-strip-html` 👍

**Comment by icksky** [comment]
@revelt `string-strip-html` is a great project. My project is based on Quasar (An UI framework). When I update typescript to `^4.2.3`, my project is broken (node out of memory). Finally, I found that typescript's version of Quasar should be lower than `4.1.0`. So I install `typescript 4.0.6`, and this version is compatible with your project.

So I think it should be that the version of TS is not compatible, not the issue of code.
Thanks~
