### ISSUE TITLE
string-strip-html ignoreTags but remove inline-style

### ISSUE THREAD

**Issue by jokel81** [codsen/codsen#40]
Hi there

I have a html string where i want to keep only some tags but remove also their inline-style.
I use this options: {'ignoreTags': ['ul','ol','li','br','p']}
The result contains:
`<ul style="color: rgb(68, 68, 68); ..."><li>...</li></ul>`

So my question is how to remove the inline style and keep only the pure tag.

Thanks for any advice.

Best regards
Jokel

**Comment by revelt** [comment]
hi @jokel81 
It's doable via a callback, `opts.cb()`. I can be done two ways actually:

1. Don't ignore any tags, don't use `opts.ignoreTags` — just pretend you're stripping everything, but listen within callback what comes in, and override the deletion, pushing third value "to add" into "rangesArr". And that value is `<${tag.name}>`
https://stackblitz.com/edit/codsen-40?file=index.js

2. You could keep using `opts.ignoreTags` but then "deleteFrom" and "deleteTo" will come blank in the callback arguments (because program doesn't want to delete recognised tags) — but you could run `forEach` on each attribute, pushing them into "rangesArr" and effectively deleting each attribute.
https://stackblitz.com/edit/codsen-40-xepkuz?file=index.js

Try both in stackblitz, use `console.log` to see what values does the callback give you.

I'll close this issue but feel free to reopen or raise a new-one.

Have a great day!
