### ISSUE TITLE
Wrong attribute detection when space at the end of attribute value (version 8.3.0)

### ISSUE THREAD

**Issue by TrumanRu** [codsen/codsen#45]
**Package's name**
string-strip-html@8.3.0

**Describe the bug**
Wrong attribute detection when space at the end of attribute value

**To Reproduce**

1. `<table style="font-family: &quot;Times New Roman&quot;;" data-mce-selected="1"><tbody><tr><td class="b-productParams ">without cover</td></tr></tbody></table>`
  (space between 'b-productParams' and the quote)
3. See error:
```
  ranges-push/Ranges/add(): [THROW_ID_10] "to" value, the second input argument, must be a natural number or zero! Currently it's of a type "number" equal to: null
  TypeError: ranges-push/Ranges/add(): [THROW_ID_10] "to" value, the second input argument, must be a natural number or zero! Currently it's of a type "number" equal to: null
     at Ranges.add (/app/node_modules/ranges-push/dist/ranges-push.cjs.js:125:17)
     at Ranges.push (/app/node_modules/ranges-push/dist/ranges-push.cjs.js:132:12)
     at /app/app/controllers/socket.js:127:33
     at Array.forEach (<anonymous>)
     at Object.cb (/app/app/controllers/socket.js:79:28)
     at _loop2 (/app/node_modules/string-strip-html/dist/string-strip-html.cjs.js:606:16)
     at stripHtml (/app/node_modules/string-strip-html/dist/string-strip-html.cjs.js:747:17)
```
Attribute values:
```json
{
  "nameStarts": 117,
  "nameEnds": 118,
  "name": "\""
}
```

**Expected behavior**
I think - no reaction to this.

**Additional context**
I need 8.x branch cause I use require() import.

**Comment by revelt** [comment]
hi! Sorry about that! Thank you for reporting, I'll fix.

**Comment by revelt** [comment]
Hm, I looked at it, it's a complex situation.

In short, you should set `opts.skipHtmlDecoding` to `true` and use it as-is.

I didn't anticipate your case and it's valid and looking back, the default `opts.skipHtmlDecoding` should have been set to `true`. But it's not worth to change now, especially in the middle of global ESM migration where vast majority of users are consuming `v8`.

What's going on is, we recursively decode HTML entities before processing the input. There are two cases:

- entity is within tag, for example, `<a href=&quot;z&quot;>` (similar to your example) — but also, that's weird cases related to infosec
- entity is outside the tag, for example, `<span>&pound;</span>`

Now, in theory, algorithm should be aware of tag locations and decode HTML only outside the tags, and upon request. But it's not the case, plus this program has a lot of whitespace control logic and a callback interface on top. 513 unit tests with 100% coverage (`c8` is [missing](https://github.com/bcoe/c8/issues/231) `else` clause so we can't do anything about it, but while we were on `istanbul` coverage was 100%).

My concern is that whatever the API currently is, it has set the expectations, especially in context of infosec. What if somebody is using this program to sanitise the inputs? That's a bad idea, this is a wrong program for that, but it's possible, right?

Also, another point, your example has very unusual pattern, escaped double quotes. This does not happen in "business as usual" commercial code, because we all use prettier and prettier autofixes that to inverted quotes pattern instead. Here's the [playground proof](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunEDGxwdHQQ5ADuECV0+eioAEJ2DOT4lGWKJ+QcPACs5DsQZXRwJRV0AIbwAHSJs2lmQrh2gWI+Gm-hWZSg+QgK3eAHMXuRROR3C4oGBqtByAAKACU5GA5Dh7wAju8Ki55JRMS8SjCXDQmvJcQBfADcBJexIR5AA2gBdNmEuhcgDUUDgK3ImDecBZP1McMxAHJSnBpYqADTkRUAVQE0gAGobDdJCBqtS83BBFdiBS8lfIEPkzYqKi8YXAAG5lcXWuWJP4AoEg9LwyglODuZwAYjq8hgEQeznc0Bg0ncLxo9wiSHIADIiS4IDAWTASvDXuRXvnC8XZSAGAAvRIvYOoAOA-DkeQlMDOagwCryJAJBIrMewiAQGEPaQvKAvOgRapgeTvSA0BJzhdLsor94KOrCQhZXCS0gAMVI+39-w700S40mOkSF24DBA6pAECqNSg8mQoDUiUULENSCD-igC4rC8ET-p+oxlmAADWcAwEIGZwNw4JwMg6Z0A68GIShaGumA4IwsgpYuHAn5wDQoxwPkhT5Nwc60m6cDnusNBvNUUAUZBlofiA1D0AA6sc8DyKRcBCOBZTVF68bIOA8hwSA4IOiUMDEGWMI8bhC4ESACgAB5CORDwAIo1jhSB4cZrolFpKmiXQwkVOUsBiWU+QwJQyBeAADJ+nkQA6YllhUKmeUUjwejhn4FkWcC6d+EEgC88jSGKjGMcJ4YFmU4a6W6Bn2UZNEgA6maUSU1GfvIllwDZKWGfhVUwC8ow+X5AVIAATJ+pYvPc5G4BANDlSARSXMJ5JwPg3UQQ5VUetRgQQk0QilJUMACBCQjxg87UOkyTJAA).

Do you see?

So, I can't/won't fix, sorry.
