### ISSUE TITLE
Incorrect comparison of Boolean values

### ISSUE THREAD

**Issue by karelkryda** [codsen/codsen#51]
**Package's name**
object-fill-missing-keys
object-merge-advanced

**Describe the bug**
When comparing two objects using the "object-fill-missing-keys" library with different Boolean values, the values are replaced despite the fact that the value is not missing (is true or false).

If one object is false and the other object is true, true is always returned.

**To Reproduce**

1. Create one object with `false` value and one object with `true` value
2. Fill object with `fillMissing(objectOne, objectTwo)`
3. See output
4. Object with `true` value is returned from method

**Expected behavior**
If the value is true or false (not missing in the object), the original value of the object should always be returned, regardless of the boolean value in the schema (the object according to which the first object fills in the missing values).

**Screenshots**

**Additional context**
An error occurs in the "object-merge-advanced" library when comparing Boolean values on [this line](https://github.com/codsen/codsen/blob/main/packages/object-merge-advanced/src/main.ts#L717).

If I use the following code, the Boolean values are returned correctly according to the first (original) object.
```js
var _currentResult25 = uni ? uniRes : i2;
return _currentResult25;
```

**Comment by revelt** [comment]
Hi Karel, sorry about that; I'll investigate.

**Comment by revelt** [comment]
Hi Karel,

Sorry for delay, at first I thought I'll have to recode the `object-fill-missing-keys` from scratch but with fresh head this morning I've been able to sort this.
I've been using this package to merge JSON data sources for email templates and they follow the data hierarchy (seen in https://codsen.com/os/object-merge-advanced#purpose). I'd prepare schema, and its placeholders would always be boolean `false` — that's lower in the "food chain" than anything on the source. Technically, this was not a bug for me, but it was for everybody, and this program didn't actually deliver what it promised — besides filling the values it was overwriting source with schema's value if the source was lower in the "values food chain" — like you rightly discovered with `{ foo: false }` vs. schema `{ foo: true }` merges.

The fix was a three-liner, I used `object-merge-advanced` callback  to conditionally merge — if types of schema and original are matching, original is kept. Otherwise, we leave it up to `object-merge-advanced` to decide (<v.10, original behaviour).

https://github.com/codsen/codsen/blob/6226d37de09759971123d56c9812e1c0e7020160/packages/object-fill-missing-keys/src/main.ts#L131-L133

I've just fixed it and released a major bump, [`v10`](https://www.npmjs.com/package/object-fill-missing-keys) please try.

Again, sorry for the bug and thanks for spotting this!
