### ISSUE TITLE
[string-remove-widows] applying to every tag?

### ISSUE THREAD

**Issue by cossssmin** [codsen/codsen#56]
**Package's name**
[string-remove-widows]

**Describe the bug**

Shouldn't this:

```html
<div style="width: 120px">
  <p>The quick brown fox jumped</p>
  <p>over the lazy dog</p>.
</div>
```

... be returned as this?

```html
<div style="width: 120px">
  <p>The quick brown fox&nbsp;jumped</p>
  <p>over the lazy&nbsp;dog</p>.
</div>
```

It currently does this:

```html
<div style="width: 120px">
  <p>The quick brown fox jumped</p>
  <p>over the lazy&nbsp;dog</p>.
</div>
```

**Comment by revelt** [comment]
Hi Cosmin! This library is low-level; it assumes the input string is the whole paragraph (which can contain tags). To achieve the result from your example, one would normally employ an AST-parser, walk the tree and process each paragraph string with `string-remove-widows`. Basically, this library is string-in, string-out, I didn't want to couple with any higher-level functions because contexts are very different.

For example, [`detergent`](https://codsen.com/os/detergent) uses this library, but piggy-backs off the `string-strip-html` (which is non-parsing), via a callback, to get visibility of the tags and then process inside.

Another example, [`remark-typography`](https://codsen.com/os/remark-typography) uses `unist-util-visit` to traverse unist AST, pick out the text nodes and pass them to this library, overwriting each node.

You need a higher-level function, parsing or non-parsing, to extract paragraph strings first.

**Comment by cossssmin** [comment]
Thanks for the detailed reply Roy, appreciate it! :)
