### ISSUE TITLE
Emailcomb leaves behind a comma when removing unused CSS classes

### ISSUE THREAD

**Issue by jkupczak** [codsen/codsen#68]
**Package's name**
Emailcomb

**Describe the bug**
Emailcomb leaves behind a comma after removing unused classes.

**To Reproduce**
`p, li, .unused-class-1, .unused-class-2 {}` becomes `p, li, {}`

**Expected behavior**
`p, li, .unused-class-1, .unused-class-2 {}` becomes `p, li {}`

**Screenshots**
https://parcel.io/e/d7e7847b-003f-4d8f-bfa8-361e3864d903?

**Comment by revelt** [comment]
hi James, sorry about that, I'll investigate.

**Comment by revelt** [comment]
hi James, sorry for taking months to fix; there've been career changes and various interesting involvements. Interestingly, the fix was three lines. The algorithm didn't anticipate `li` for example (mainly because I never put anything else than classes in head CSS) — then as a result, it didn't report the location of trailing comma after.

The pure-ESM `7.0.13` is out, I need to back-port to that to CJS `5.3.0`, probably that will be next night.

**Comment by revelt** [comment]
non-pure ESM, bundled (no dependencies) `5.3.1` has been released, I'll close
