### ISSUE TITLE
Getting a key from another object

### ISSUE THREAD

**Issue by EhsanFox** [codsen/codsen#7]
**Package's name**
json-variables

**Describe the situation**
so we know that %_var.key_& goes and gets the `key` from `var` object that is **next to where it being called**
so how we can call a `key` from like a past object,
something like this:
```
"thumbnail": {
                "url": "{{vars.thumbnail}}"
            },
```
if the `vars` object don't be in the `thumbnail` it won't work, so what should I do?

**Comment by EhsanFox** [comment]
`%_var.key_%`

**Comment by revelt** [comment]
hi EhsanFox!
If all goes well, this evening I'll make a playground for `json-variables`, it will be easier to explain. Basically, you have three options to query variables. 1) absolute path; 2) ask simply for a key name, it will "bubble up" searching all parents up to the top, then, if not found, `throw`; 3) [data containers](https://codsen.com/os/json-variables#data-containers) where you want to keep values in vicinity.

If that's all right, I'll answer either late today or early tomorrow with some examples straight from a playground.

**Comment by revelt** [comment]
OK, here's a [playground](https://codsen.com/os/json-variables/play).

**Comment by revelt** [comment]
I set the realistically-looking scenario as a default preset:

```json
{
    "greeting": "{% if customer.vip %}%%-namePresent-%%{% else %}%%-nameAbsent-%%{% endif %}",
    "namePresent": "Hi {{ customer.firstName }}, here's your coupon for your next purchase!",
    "nameAbsent": "Here's a coupon for your next purchase."
}
```

above, we have Nunjucks/Jinja logic, if-else statement, in JSON content file. Key `greeting` references other keys, inserting values between if-else statements. I'm addressing the variables by simply the key name, program first "looks" at the current object, in this case it finds the values and finishes. Otherwise, it would "bubble" up through parent objects:

```json
{
    "x": {
        "y": {
            "greeting": "{% if customer.vip %}%%-namePresent-%%{% else %}%%-nameAbsent-%%{% endif %}",
            "namePresent": "Hi %%-firstName-%%, here's your coupon for your next purchase!",
            "nameAbsent": "Here's a coupon for your next purchase."
        }
    },
    "firstName": "{{ customer.firstName }}"
}
```

Notice how above, we referenced a key name `%%-firstName-%%`, then if "bubbled up" to the root level, found it, then resolved it. I haven't added the wrapping toggle yet, but if `json-variables` wrapping was enabled, above, you could just put `"firstName": "customer.firstName"` and double curlies would get added automatically.

Try some examples in the playground, see how it goes.

Also, since I don't have enough time to write safeguards to allow `eval`, the input is JSON, which has to be parse-able. The `json-variables` program takes parsed plain objects, not JSON strings. But playground takes JSON string. Do validate the JSON strings — I prefer https://jsonformatter.curiousconcept.com/ — if the files are realistic, big, it might help.

Check the [playground](https://codsen.com/os/json-variables/play), see how it goes.

**Comment by revelt** [comment]
hi @EhsanFox how is it going? Let me know if I can help further or if we can close the ticket.
